site_name: Virus Epidemiology Group Documentation

theme:
  name: material
  features:
    - search.suggest
    - navigation.tracking
    - navigation.instant
    - header.autohide
  language: en
  palette:
    primary: blue
    accent: purple
  font: false

nav:
  - Home: index.md
  - GitLab: gitlab.md
  - R: r.md
  - BIH-Cluster: bih-cluster.md
  - Data Organisation: data-organisation.md
  - Documentation: documentation.md
  - 'Analysis Pipelines':
    - 'Virus Discovery': virus-identification-pipelines/virus-discovery.md
    - 'Virus Assembly': virus-identification-pipelines/virus-assembly.md
  - 'Useful Software':
    - 'Bowtie 2': useful-software/bowtie-2.md
    - 'DIAMOND': useful-software/diamond.md
    - 'fastp': useful-software/fastp.md
    - 'ffq': useful-software/ffq.md
    - 'gget': useful-software/gget.md
    - 'Kraken 2': useful-software/kraken-2.md
    - 'Serratus': useful-software/serratus.md
    - 'SPAdes': useful-software/spades.md
  - To-Do: todo.md

repo_url: ""
site_url: ""
use_directory_urls: false

markdown_extensions:
  - toc:
      permalink: "$"
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - print-site
