site_name: Virus Epidemiology Group Documentation

theme:
  name: material
  features:
    - search.suggest
    - navigation.tracking
    - navigation.instant
    - header.autohide
  language: en
  palette:
    primary: blue
    accent: purple
  font: false

nav:
  - 'Home': index.md
  - 'New Members': new-members.md
  - 'GitHub': github.md
  - 'GitLab': gitlab.md
  - 'R': r.md
  - 'BIH-Cluster': 
    - 'Introduction': bih-cluster/bih-cluster-introduction.md
    - 'Filesystem mount': bih-cluster/filesystem-mount-sshfs.md 
  - 'Data Organisation': 
    - 'File system': data-organisation/file-system.md
    - 'NGS runs': data-organisation/ngs-runs.md
  - 'Documentation': documentation.md
  - 'Analysis Pipelines':
    - 'Virus Discovery': virus-identification-pipelines/virus-discovery.md
    - 'Virus Assembly': virus-identification-pipelines/virus-assembly.md
  - 'Analysis SOP':
    - 'MSA using reference': analysis-sop/mafft-with-reference.md
    - 'BCL to FASTQ conversion': analysis-sop/bcl-fastq-conversion.md
    - 'RStudio on HPC cluster': analysis-sop/rstudio-cluster.md
  - 'Useful Software':
    - 'Bowtie 2': useful-software/bowtie-2.md
    - 'DIAMOND': useful-software/diamond.md
    - 'fastp': useful-software/fastp.md
    - 'ffq': useful-software/ffq.md
    - 'gget': useful-software/gget.md
    - 'Kraken 2': useful-software/kraken-2.md
    - 'Serratus': useful-software/serratus.md
    - 'Snakemake': useful-software/snakemake.md
    - 'SPAdes': useful-software/spades.md
  - 'To-Do': todo.md

repo_url: ""
site_url: ""
use_directory_urls: false

markdown_extensions:
  - toc:
      permalink: "$"
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html


plugins:
  - search
  - print-site
